name: example
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  responsive_widgets_prefix:
    path: ..

  cupertino_icons: ^1.0.2

dev_dependencies:
  
  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter

  integration_test_preview: 0.0.2

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/the-mac-avatar.jpeg
